import { Geist, Geist_Mono } from "next/font/google";
import AOSProvider from "@/components/AOSProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rifky Afif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth` }
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <AOSProvider>
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
